#!/usr/bin/env python3
"""Derive protocol addresses and item eligibility from this exact pret build."""
import pathlib, re, sys, zlib
root = pathlib.Path(__file__).resolve().parents[1]
out = root.parent / 'pkai/generated'
out.mkdir(parents=True, exist_ok=True)
def write(path, text):
    if not path.exists() or path.read_text() != text: path.write_text(text)
def items():
    source = (root/'engine/battle/trainer_ai.asm').read_text()
    pointers = re.findall(r'dbw (\d+), (\w+) ; (\w+)', (root/'data/trainers/ai_pointers.asm').read_text())
    names = {'FullRestore':'FULL_RESTORE', 'Potion':'POTION', 'SuperPotion':'SUPER_POTION', 'HyperPotion':'HYPER_POTION', 'FullHeal':'FULL_HEAL', 'GuardSpec':'GUARD_SPEC', 'XAttack':'X_ATTACK', 'XDefend':'X_DEFEND', 'XSpeed':'X_SPEED'}
    rows = []
    for count, routine, cls in pointers:
        body = re.search(r'^'+routine+r':\n(.*?)(?=^\w+:)', source, re.M|re.S)[1]
        uses = re.findall(r'jp(?: c,)? (AIUse\w+)', body)
        assert len(uses) <= 1, (routine, uses)
        item = names[uses[0][5:]] if uses else '0'
        threshold = re.search(r'ld a, (\d+)\n\s*call AICheckIfHPBelowFraction', body)
        fraction = int(threshold[1]) if threshold and uses else 0
        status = int(routine == 'BrockAI')
        rows.append((count,item,fraction,status,cls))
    write(root/'data/trainers/ai_items.asm', '; Generated by tools/generate_ai.py --items. item, HP divisor, status required.\nAIItemTable::\n' + ''.join(f'\tdb {i}, {f}, {s} ; {c}\n' for _,i,f,s,c in rows))
    return rows
rows=items()
if '--items' in sys.argv: sys.exit()
syms={}
for line in (root/'pokered-ai.sym').read_text().splitlines():
    m=re.fullmatch(r'([\da-fA-F]+):([\da-fA-F]+) (\S+)',line)
    if m: syms[m[3]]=(int(m[1],16),int(m[2],16))
required='wEnemyMons wEnemyMon wBattleMon wPartyMons wPartyCount wEnemyPartyCount wEnemyMonPartyPos wEnemyDisabledMove wEnemySelectedMove wEnemyMoveListIndex wAICount wTrainerClass wIsInBattle wLinkState wPlayerMonStatMods wEnemyMonStatMods wPlayerBattleStatus1 wPlayerBattleStatus2 wPlayerBattleStatus3 wEnemyBattleStatus1 wEnemyBattleStatus2 wEnemyBattleStatus3 wEnemySubstituteHP wPlayerSubstituteHP wDamage wCriticalHitOrOHKO wMoveMissed wTypeEffectiveness wPlayerMoveNum wEnemyMoveNum wPlayerUsedMove wEnemyUsedMove wAIAction wAIDisarmed wAIRoundOpen wAISwitchTarget wAIReplacement wAIWaiting wPlayerMonNumber hWhoseTurn hRandomAdd hRandomSub wEnemyConfusedCounter wEnemyToxicCounter wPlayerMovePower wPlayerMoveType wPlayerMoveEffect wPlayerMoveAccuracy wEnemyMovePower wEnemyMoveType wEnemyMoveEffect wEnemyMoveAccuracy wPlayerMoveNum wEnemyMoveNum wDamageMultipliers wMoveType wCurSpecies wMonHeader wMonHBaseSpeed wPlayerSelectedMove wEnemySelectedMove wPlayerMoveListIndex wEnemyMoveListIndex wPlayerMonMinimized wEnemyMonMinimized hLoadedROMBank wCurOpponent wTrainerNo wLoneAttackNo wRivalStarter wCurEnemyLevel wMonDataLocation wCurPartySpecies wTrainerBaseMoney wAmountMoneyWon wEnemyPartySpecies'.split()
# Generate all fields too: struct offsets are never copied from a different checkout.
required += [n for n in syms if n.startswith(('wEnemyMon','wBattleMon','wPartyMon')) and '.' not in n]
header='#pragma once\n#include <cstdint>\nnamespace pkai::symbols {\n'
for n in sorted(set(required)):
    bank,addr=syms[n]; header+=f'inline constexpr uint16_t {n} = 0x{addr:04x};\ninline constexpr uint8_t {n}_bank = {bank};\n'
write(out/'wram_symbols.h',header+'}\n')
rom='#pragma once\n#include <cstdint>\nnamespace pkai::tables {\nstruct Address { uint8_t bank; uint16_t address; constexpr unsigned offset() const { return bank ? bank * 0x4000u + address - 0x4000u : address; } };\n'
for n in sorted(syms):
    if n in ['BaseStats','MewBaseStats','PokedexOrder','TypeEffects','Moves','TrainerAIPointers','AIItemTable','StatModifierRatios','HighCriticalMoves','StartBattle','MainInBattleLoop','SelectEnemyMove','EnemySendOutFirstMon','GetDamageVarsForPlayerAttack','GetDamageVarsForEnemyAttack','CalculateDamage','AdjustDamageForMoveType','CalcHitChance','CriticalHitTest','ReadTrainer','TrainerDataPointers','LoneMoves','TeamMoves'] or (n.startswith('AI') and '.' not in n) or '.AIEventHook_' in n:
        b,a=syms[n]
        ident=n.replace('.', '__')
        if a < 0x8000: rom+=f'inline constexpr Address {ident}{{{b},0x{a:04x}}};\n'
rom+=f'inline constexpr unsigned trainer_classes = {len(rows)};\n'
# Trainer class names in id order (index 0 is NOBODY), from constants/trainer_constants.asm.
classes=re.findall(r'^\ttrainer_const (\w+)', (root/'constants/trainer_constants.asm').read_text(), re.M)
assert len(classes)==len(rows)+1, (len(classes), len(rows))
rom+='inline constexpr const char* trainer_class_names[] = {'+', '.join(f'"{c}"' for c in classes)+'};\n'
rom+=f'inline constexpr uint32_t rom_crc32 = 0x{zlib.crc32((root/"pokered-ai.gbc").read_bytes()):08x}u;\n'
write(out/'rom_tables.h',rom+'}\n')
print('Generated symbols and CRC for pokered-ai.gbc')
