"""Generate sim/gen1data.py from the vendored engine's own data files.

Sources of truth:
  vendor/engine/src/data/data.json          (species order/stats/types, move order/pp)
  vendor/engine/src/lib/gen1/data/moves.zig (move bp/accuracy/type/effect)
  vendor/engine/src/lib/gen1/data/types.zig (type chart)

Run: uv run python tools/gen_data.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / "vendor" / "engine"
OUT = ROOT / "sim" / "gen1data.py"

EFFECTIVENESS = {"S": 2.0, "N": 1.0, "R": 0.5, "I": 0.0}


def main() -> None:
    gen1 = json.loads((ENGINE / "src" / "data" / "data.json").read_text())[0]
    types: list[str] = gen1["types"]
    species: dict = gen1["species"]
    move_pp: dict = gen1["moves"]

    moves_zig = (ENGINE / "src" / "lib" / "gen1" / "data" / "moves.zig").read_text()
    data_block = moves_zig.split("const DATA = ")[1]
    entries = re.findall(
        r"\.\{\s*\.effect = \.(\w+),\s*\.bp = (\d+),\s*(?:\.type = \.(\w+),\s*\.accuracy = percent\((\d+)\),|\.accuracy = percent\((\d+)\),\s*\.type = \.(\w+),)",
        data_block,
    )
    move_names = list(move_pp)
    assert len(entries) >= len(move_names), (len(entries), len(move_names))

    types_zig = (ENGINE / "src" / "lib" / "gen1" / "data" / "types.zig").read_text()
    chart_rows = re.findall(r"\[_\]Effectiveness\{([^}]+)\},\s*//", types_zig)
    assert len(chart_rows) == len(types), len(chart_rows)
    chart = [
        [EFFECTIVENESS[c.strip()] for c in row.split(",") if c.strip()]
        for row in chart_rows
    ]
    assert all(len(r) == len(types) for r in chart)

    lines = [
        '"""Gen 1 data tables. GENERATED by tools/gen_data.py - do not edit."""',
        "",
        f"TYPES = {types!r}",
        "",
        "# name -> (id, base_hp, base_atk, base_def, base_spe, base_spc, type1, type2)",
        "SPECIES = {",
    ]
    for i, (name, d) in enumerate(species.items()):
        s = d["stats"]
        t = d["types"]
        if len(t) == 1:
            t = [t[0], t[0]]
        lines.append(
            f"    {name!r}: ({i + 1}, {s['hp']}, {s['atk']}, {s['def']}, "
            f"{s['spe']}, {s['spc']}, {t[0]!r}, {t[1]!r}),"
        )
    lines += ["}", "", "# name -> (id, base_pp, bp, accuracy, type, effect)", "MOVES = {"]
    for i, name in enumerate(move_names):
        effect, bp, t1, a1, a2, t2 = entries[i]
        mtype = t1 or t2
        acc = a1 or a2
        lines.append(
            f"    {name!r}: ({i + 1}, {move_pp[name]}, {int(bp)}, {int(acc)}, "
            f"{mtype!r}, {effect!r}),"
        )
    lines += [
        "}",
        "",
        "# TYPE_CHART[attacking][defending] -> multiplier",
        "TYPE_CHART = {",
    ]
    for i, atk in enumerate(types):
        row = ", ".join(f"{types[j]!r}: {chart[i][j]}" for j in range(len(types)))
        lines.append(f"    {atk!r}: {{{row}}},")
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(species)} species, {len(move_names)} moves)")


if __name__ == "__main__":
    main()
