import { StyleSheet } from "react-native";

export const dialogStyles = StyleSheet.create({
  settingsBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    backgroundColor: "rgba(20, 20, 26, 0.6)",
  },
  settingsCard: {
    backgroundColor: "#d8d4c6",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#a59f8d",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
  },
  settingsCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  settingsTitle: {
    color: "#31316f",
    fontSize: 18,
    fontWeight: "800",
    fontStyle: "italic",
    letterSpacing: 1,
    userSelect: "none",
  },
  settingsCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#c8c3b4",
    borderWidth: 1,
    borderColor: "#aaa596",
  },
  settingsCloseBtnText: {
    color: "#4c4a55",
    fontSize: 14,
    fontWeight: "800",
    userSelect: "none",
  },
  settingsField: {
    marginBottom: 14,
  },
  settingsFieldLabel: {
    color: "#6b665a",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 6,
    userSelect: "none",
  },
  settingsInput: {
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#aaa596",
    backgroundColor: "#efece3",
    paddingHorizontal: 12,
    fontSize: 14,
    color: "#33333c",
  },
  settingsToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingsToggleHint: {
    marginTop: 2,
    color: "#8a8577",
    fontSize: 11,
    lineHeight: 15,
    userSelect: "none",
  },
  settingsSyncSection: {
    marginTop: 6,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#c0bbac",
  },
  pullButton: {
    height: 44,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#9a1f4c",
    borderWidth: 1,
    borderColor: "#6f153a",
  },
  pullButtonText: {
    color: "#f2d9e2",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1.5,
    fontStyle: "italic",
    userSelect: "none",
  },
  pullHint: {
    marginTop: 10,
    color: "#6b665a",
    fontSize: 11,
    lineHeight: 15,
    userSelect: "none",
  },
  pullError: {
    marginTop: 10,
    color: "#a3341f",
    fontSize: 12,
    fontWeight: "700",
    userSelect: "none",
  },
  pullOk: {
    marginTop: 10,
    color: "#2f6b3a",
    fontSize: 12,
    fontWeight: "800",
    userSelect: "none",
  },
  pullList: {
    marginTop: 8,
    gap: 5,
  },
  pullRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pullBadge: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.5,
    color: "#fff",
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
    userSelect: "none",
  },
  pullBadgeNew: {
    backgroundColor: "#2f6b3a",
  },
  pullBadgeUpdate: {
    backgroundColor: "#b5761c",
  },
  pullItemLabel: {
    flex: 1,
    color: "#4c4a55",
    fontSize: 12,
    fontWeight: "600",
    userSelect: "none",
  },
  pullItemVer: {
    color: "#6b665a",
    fontSize: 10,
    fontVariant: ["tabular-nums"],
    userSelect: "none",
  },

});
